defmodule Foeder.Ash.Repo.Migrations.TodoUserRelation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
#    create table(:users, primary_key: false) do
#      add :id, :uuid, null: false, primary_key: true
#      add :email, :text, null: false
#    end

    alter table(:todo) do
      add :user_id,
          references(:users, column: :id, name: "todo_user_id_fkey", type: :bigint, prefix: "public")
    end
  end

  def down do
    drop constraint(:todo, "todo_user_id_fkey")

    alter table(:todo) do
      remove :user_id
    end
  end
end
