defmodule Foeder.Ash.Repo.Migrations.TodoTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:todo, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :text, :text, null: false
      add :done, :boolean, null: false, default: false
    end
  end

  def down do
    drop table(:todo)
  end
end