defmodule Foeder.Ash.Repo.Migrations.TodoPriority do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:todo) do
      add :high_priority, :boolean, default: false
    end
  end

  def down do
    alter table(:todo) do
      remove :high_priority
    end
  end
end